name: build and test

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs: 
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 20
      - run: npm i

      

        




