name: CI - Front-only avec Cypress E2E

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer les dépendances
        run: npm install

      - name: Installer Tailwind CSS
        run: npm install --save-dev @tailwindcss/oxide

      - name: Build de l'app Next.js
        run: npm run build

      - name: Démarrer l'app en background
        run: npm run start &
        env:
          NODE_ENV: production

      - name: Attendre que l'app réponde (localhost:3000)
        run: npx wait-on http://localhost:3000

      - name: Lancer les tests Cypress
        run: npx cypress run
